const b=await import("/app/node_modules/@whiskeysockets/baileys/lib/index.js");
const m=b.makeWASocket||b.default?.makeWASocket;
const u=b.useMultiFileAuthState||b.default?.useMultiFileAuthState;
const f=b.fetchLatestBaileysVersion||b.default?.fetchLatestBaileysVersion;
const k=b.makeCacheableSignalKeyStore||b.default?.makeCacheableSignalKeyStore;
const{state:s}=await u("/home/openclaw/.openclaw/credentials/whatsapp/default/");
const{version:v}=await f();
const n=()=>{};
const l=()=>({level:"silent",trace:n,debug:n,info:n,warn:console.warn,error:console.error,fatal:console.error,child:function(){return this}});
const sock=m({auth:{creds:s.creds,keys:k(s.keys,l())},version:v,printQRInTerminal:false,browser:["dbg","t","1"],markOnlineOnConnect:true,syncFullHistory:false,shouldSyncHistoryMessage:()=>false,logger:l()});
sock.ev.on("connection.update",x=>{console.log("CONN:"+JSON.stringify(x));if(x.connection==="open"){console.log("Sending test message to family group...");sock.sendMessage("120363426564202103@g.us",{text:"🤖 test"}).then(r=>console.log("SENT:"+JSON.stringify({id:r?.key?.id}))).catch(e=>console.error("SEND ERR:"+e))}if(x.connection==="close"){process.exit(1)}});
sock.ev.on("messages.upsert",x=>{console.log(">>> MSG:"+JSON.stringify({t:x.type,n:x.messages?.length,msgs:x.messages?.map(m=>({id:m.key?.id,from:m.key?.remoteJid,fromMe:m.key?.fromMe,text:m.message?.conversation||m.message?.extendedTextMessage?.text||"[media]"}))}))});
sock.ev.on("presence.update",()=>console.log("PRES"));
sock.ev.on("messaging-history.set",x=>console.log("HISTORY:"+JSON.stringify({chats:x.chats?.length,contacts:x.contacts?.length,messages:x.messages?.length})));
setInterval(()=>{try{sock.ev.flush()}catch(e){}},5e3);
console.log("Connected! Waiting 120s for messages... Ask wife to send now!");
setTimeout(()=>{console.log("Timeout - no messages received in 120s");process.exit(0)},120000);
