apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: TENANT_NAMESPACE

resources:
  - ../../base
  - namespace.yaml
  - network-policy.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - hpa.yaml
