apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aiplatform-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: cosmos-endpoint
          objectType: secret
        - |
          objectName: entra-client-id
          objectType: secret
        - |
          objectName: entra-tenant-id
          objectType: secret
        - |
          objectName: workload-client-id
          objectType: secret
        - |
          objectName: service-bus-namespace
          objectType: secret
        - |
          objectName: appinsights-connection-string
          objectType: secret
        - |
          objectName: platform-admin-emails
          objectType: secret
        - |
          objectName: entra-admin-group-id
          objectType: secret
        - |
          objectName: entra-client-secret
          objectType: secret
        - |
          objectName: jira
          objectType: secret
  secretObjects:
    - secretName: aiplatform-secrets
      type: Opaque
      data:
        - objectName: cosmos-endpoint
          key: COSMOS_ENDPOINT
        - objectName: jira
          key: JIRA_API_TOKEN
        - objectName: entra-client-id
          key: AZURE_CLIENT_ID
        - objectName: entra-tenant-id
          key: AZURE_TENANT_ID
        - objectName: workload-client-id
          key: AZURE_WORKLOAD_CLIENT_ID
        - objectName: service-bus-namespace
          key: SERVICE_BUS_NAMESPACE
        - objectName: appinsights-connection-string
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
        - objectName: platform-admin-emails
          key: PLATFORM_ADMIN_EMAILS
        - objectName: entra-admin-group-id
          key: ENTRA_ADMIN_GROUP_ID
        - objectName: entra-client-secret
          key: ENTRA_CLIENT_SECRET
